Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -47,3 +47,44 @@ jobs:
         echo "$OUTPUT" | grep -q "x1 = -5.00000" || (echo "x1 test failed"; exit 1)
         echo "$OUTPUT" | grep -q "x2 = 5.00000" || (echo "x2 test failed"; exit 1)
         echo "Solver test passed!"
+
+  build-windows:
+    runs-on: windows-latest
+
+    steps:
+    - uses: actions/checkout@v2
+
+    - name: Setup MSVC Developer Command Prompt
+      uses: ilammy/msvc-dev-cmd@v1
+
+    - name: Add CMake to PATH
+      uses: lukka/get-cmake@v3
+
+    - name: Create Build Directory
+      run: mkdir build
+
+    - name: Configure CMake
+      working-directory: ./build
+      run: cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
+
+    - name: Build
+      working-directory: ./build
+      run: cmake --build . --config ${{ env.BUILD_TYPE }}
+
+    - name: Run Hello World Test
+      working-directory: ./build
+      shell: pwsh
+      run: |
+        .\hello_world_application\hello_world.exe | Select-String "hello, world!" > $null
+        Write-Output "Hello World test passed!"
+
+    - name: Run Solver Test
+      working-directory: ./build
+      shell: pwsh
+      run: |
+        Write-Output "Testing equation solver:"
+        $output = .\solver_application\solver.exe
+        Write-Output $output
+        if ($output -notmatch "x1 = -5.00000") { Write-Error "x1 test failed"; exit 1 }
+        if ($output -notmatch "x2 = 5.00000") { Write-Error "x2 test failed"; exit 1 }
+        Write-Output "Solver test passed!"
